### ISSUE TITLE
This plugin generated a warning from the characteristic 'Brightness'

### ISSUE THREAD

**Issue by andyrooo82** [scaliebe/homebridge-lifesmart-cololightpro#1]
love the plugin - working great except I get the following error

[homebridge-lifesmart-cololightpro] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.

I have read the wiki (url in the error message) and it say's that the end user should run as a child bridge (which I am) but to also log it with the plugin developer which is why I'm logging this issue.

**Comment by NERVEbing** [comment]
Me too, but I still thank the author.

**Comment by scaliebe** [comment]
This should be fixed with update to homebridge-lifesmart-cololightpro v1.0.4
