### ISSUE TITLE
This Plugin Doesn't Control my ColoLight

### ISSUE THREAD

**Issue by Justintime50** [scaliebe/homebridge-lifesmart-cololightpro#2]
I have a [ColoLight](https://www.amazon.com/LifeSmart-Hexagonal-Cololight-Quantum-Assistant/dp/B088TGKSB6/ref=sr_1_1_sspa?crid=3N0VPRADOZ5V1&keywords=cololight&qid=1668205139&sprefix=cololigh%2Caps%2C140&sr=8-1-spons&psc=1) that isn't pairing with Homebridge. I've added this plugin to Homebridge but am not sure how to properly configure it to control the light correctly. The README doesn't have any information on the subject. Can you help provide some additional details and can we get them added to the README?

I can add it to the Home app but then the slider doesn't change the brightness of the Cololight nor does asking Siri to turn it off or on do anything.

**Comment by scaliebe** [comment]
You only need to add the local IP address of ColoLight to the config.

**Comment by Justintime50** [comment]
That did the trick, thank you! I put up a little PR to update the README to help clarify the setup for future travelers. Thanks for the plugin!
